/**
 * 粒子与背景特效库 · 效果定义
 *
 * 设计要点：每个效果的“唯一真源”是一段能独立运行的 HTML 文件，
 * 页面里的预览用 iframe(srcdoc) 加载的正是同一份 HTML，
 * 所以「预览看到的」与「下载得到的」保证逐字一致，不存在两套实现走偏的问题。
 *
 * 效果代码运行在共享外壳里，外壳负责：画布尺寸与 DPR、帧循环、帧间隔 dt、
 * 暂停/恢复、配色解析、值噪声、指针坐标。效果只需要实现两个函数：
 *
 *   fxSetup()      初始化（挂载时、尺寸变化时、密度变化时会被调用，必须可重复执行）
 *   fxFrame(t)     每帧绘制，t 为累计运行秒数（暂停时不推进）
 *   fxPalette()    可选。配色变化时调用，用于重建缓存了颜色的资源（如精灵图）
 *
 * 效果代码里不要出现反引号和 ${ }（整份 HTML 由模板字符串拼装）。
 */

export type EffectCategory = "particle" | "background"

export type EffectOptions = {
  /** 速度倍率 */
  speed: number
  /** 密度倍率 */
  density: number
  /** 配色索引 */
  palette: number
}

export type ControlKey = keyof EffectOptions

export type EffectDef = {
  id: string
  name: string
  desc: string
  category: EffectCategory
  tags: string[]
  /** 该效果真正会用到的调节项，UI 只渲染这些 */
  controls: ControlKey[]
  defaults: Partial<EffectOptions>
  script: string
}

export const DEFAULT_OPTIONS: EffectOptions = { speed: 1, density: 1, palette: 0 }

export const PALETTES: { name: string; bg: string; colors: [string, string, string] }[] = [
  { name: "极光", bg: "#05070a", colors: ["#58e2c0", "#6a8bff", "#b06ef3"] },
  { name: "霓虹", bg: "#0a0510", colors: ["#ff3d8b", "#8b5bff", "#00e5ff"] },
  { name: "落日", bg: "#0d0605", colors: ["#ff6a3d", "#ffb057", "#ff4d6d"] },
  { name: "深海", bg: "#030812", colors: ["#2ad4ff", "#4c6fff", "#7dfcc8"] },
  { name: "暗金", bg: "#0a0805", colors: ["#ffd166", "#f4a261", "#e76f51"] },
  { name: "夜紫", bg: "#08060f", colors: ["#a78bfa", "#f472b6", "#38bdf8"] },
]

/* ============================ 共享外壳 ============================ */

const BASE_CSS = [
  "*{margin:0;padding:0;box-sizing:border-box}",
  "html,body{height:100%;overflow:hidden;background:#05070a}",
  "body{touch-action:none;-webkit-user-select:none;user-select:none;cursor:crosshair}",
  "canvas{position:fixed;inset:0;width:100%;height:100%;display:block}",
].join("\n")

/**
 * 生成可直接运行（也能直接双击打开）的单文件 HTML。
 */
export function buildEffectHtml(id: string, options?: Partial<EffectOptions>): string {
  const def = EFFECTS.find((item) => item.id === id)
  if (!def) throw new Error("未知特效：" + id)

  const opt: EffectOptions = { ...DEFAULT_OPTIONS, ...def.defaults, ...options }

  const runtime = [
    "(function () {",
    '  "use strict";',
    "  var PALETTES = " + JSON.stringify(PALETTES) + ";",
    "  var FX = {",
    '    canvas: document.getElementById("fx"),',
    "    ctx: null,",
    "    W: 1, H: 1, dpr: 1,",
    "    t: 0, dt: 0.016, frames: 0, paused: false,",
    "    opt: " + JSON.stringify(opt) + ",",
    "    pointer: { x: -9999, y: -9999, has: false, down: false }",
    "  };",
    "  window.FX = FX;",
    "  /* 出问题时不静默：着色器编译失败之类的错误都记在这里，便于排查 */",
    "  FX.errors = [];",
    "  window.addEventListener(\"error\", function (e) {",
    "    FX.errors.push(String((e && (e.message || e.error)) || e));",
    "  });",
    "",
    "  /* ---------- 配色 ---------- */",
    "  function hexToRgb(h) {",
    "    var v = parseInt(h.slice(1), 16);",
    "    return [(v >> 16) & 255, (v >> 8) & 255, v & 255];",
    "  }",
    "  FX.bgHex = \"#000000\";",
    "  FX.bgRGB = [0, 0, 0];",
    "  FX.colorsHex = [];",
    "  FX.colorsRGB = [];",
    "  FX.fade = function (a) {",
    '    return "rgba(" + FX.bgRGB[0] + "," + FX.bgRGB[1] + "," + FX.bgRGB[2] + "," + a + ")";',
    "  };",
    "  /* FX.color(i, a) 取配色里第 i 个颜色，a 省略时为不透明 */",
    "  FX.color = function (i, a) {",
    "    var c = FX.colorsRGB[((i % FX.colorsRGB.length) + FX.colorsRGB.length) % FX.colorsRGB.length];",
    '    return a === undefined ? "rgb(" + c[0] + "," + c[1] + "," + c[2] + ")" : "rgba(" + c[0] + "," + c[1] + "," + c[2] + "," + a + ")";',
    "  };",
    "  function applyPalette() {",
    "    var p = PALETTES[FX.opt.palette] || PALETTES[0];",
    "    FX.bgHex = p.bg;",
    "    FX.bgRGB = hexToRgb(p.bg);",
    "    FX.colorsHex = p.colors.slice();",
    "    FX.colorsRGB = p.colors.map(function (c) { return hexToRgb(c); });",
    "    document.body.style.background = p.bg;",
    "  }",
    "  applyPalette();",
    "",
    "  /* ---------- 值噪声：给效果做平滑游走用 ---------- */",
    "  function ihash(x, y) {",
    "    var n = (x * 374761393 + y * 668265263) | 0;",
    "    n = (n ^ (n >> 13)) | 0;",
    "    n = (n * 1274126177) | 0;",
    "    return ((n ^ (n >> 16)) >>> 0) / 4294967296;",
    "  }",
    "  FX.noise2 = function (x, y) {",
    "    var xi = Math.floor(x), yi = Math.floor(y);",
    "    var xf = x - xi, yf = y - yi;",
    "    var u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);",
    "    var a = ihash(xi, yi), b = ihash(xi + 1, yi), c = ihash(xi, yi + 1), d = ihash(xi + 1, yi + 1);",
    "    return (a + (b - a) * u) * (1 - v) + (c + (d - c) * u) * v;",
    "  };",
    "",
    "  /* ---------- 尺寸与指针 ---------- */",
    "  FX.dpr = Math.min(window.devicePixelRatio || 1, 2);",
    "  function resize() {",
    "    var w = FX.canvas.clientWidth || window.innerWidth || 1;",
    "    var h = FX.canvas.clientHeight || window.innerHeight || 1;",
    "    FX.W = w;",
    "    FX.H = h;",
    "    /* 缩放系数：面板预览与全屏尺寸差别很大，粒子类效果按这两个值适配 */",
    "    FX.scale = Math.max(0.35, Math.min(2.2, Math.min(w, h) / 900));",
    "    FX.k = Math.max(0.5, Math.min(2.4, (w * h) / 900000));",
    "    var pw = Math.max(1, Math.round(w * FX.dpr));",
    "    var ph = Math.max(1, Math.round(h * FX.dpr));",
    "    if (FX.canvas.width !== pw || FX.canvas.height !== ph) {",
    "      FX.canvas.width = pw;",
    "      FX.canvas.height = ph;",
    "    }",
    "    if (FX.ctx && FX.ctx.setTransform) FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
    "  }",
    "  /* WebGL 里 y 轴朝上，取归一化坐标用这两个 */",
    "  FX.nx = function () { return FX.pointer.x / Math.max(1, FX.W); };",
    "  FX.ny = function () { return 1 - FX.pointer.y / Math.max(1, FX.H); };",
    "",
    "  window.addEventListener(\"pointermove\", function (e) {",
    "    FX.pointer.x = e.clientX;",
    "    FX.pointer.y = e.clientY;",
    "    FX.pointer.has = true;",
    "  }, { passive: true });",
    "  window.addEventListener(\"pointerdown\", function (e) {",
    "    FX.pointer.down = true;",
    "    FX.pointer.x = e.clientX;",
    "    FX.pointer.y = e.clientY;",
    "    FX.pointer.has = true;",
    "  }, { passive: true });",
    "  window.addEventListener(\"pointerup\", function () { FX.pointer.down = false; }, { passive: true });",
    "  window.addEventListener(\"pointerleave\", function () {",
    "    FX.pointer.has = false;",
    "    FX.pointer.x = -9999;",
    "    FX.pointer.y = -9999;",
    "  });",
    "",
    "  /* ---------- 生命周期 ---------- */",
    "  function setup() {",
    "    resize();",
    "    if (typeof fxSetup === \"function\") fxSetup();",
    "  }",
    "",
    "  var reduce = window.matchMedia(\"(prefers-reduced-motion: reduce)\").matches;",
    "  var freezeAfter = reduce ? 90 : 0;",
    "  var last = 0;",
    "",
    "  function loop(now) {",
    "    var tn = now * 0.001;",
    "    var dt = last ? Math.min(0.05, tn - last) : 0.016;",
    "    last = tn;",
    "    if (!FX.paused) {",
    "      FX.dt = dt;",
    "      FX.t += dt;",
    "      FX.frames += 1;",
    "      if (typeof fxFrame === \"function\") fxFrame(FX.t);",
    "      if (freezeAfter && FX.frames >= freezeAfter) FX.paused = true;",
    "    }",
    "    requestAnimationFrame(loop);",
    "  }",
    "",
    "  window.addEventListener(\"message\", function (e) {",
    "    var d = e.data;",
    "    if (!d || typeof d !== \"object\") return;",
    "    if (d.type === \"fx:pause\") FX.paused = true;",
    "    else if (d.type === \"fx:resume\") { FX.paused = false; FX.frames = 0; }",
    "    else if (d.type === \"fx:options\" && d.options) {",
    "      var reset = false;",
    "      if (typeof d.options.speed === \"number\") FX.opt.speed = d.options.speed;",
    "      if (typeof d.options.density === \"number\" && d.options.density !== FX.opt.density) {",
    "        FX.opt.density = d.options.density;",
    "        reset = true;",
    "      }",
    "      if (typeof d.options.palette === \"number\" && d.options.palette !== FX.opt.palette) {",
    "        FX.opt.palette = d.options.palette;",
    "        applyPalette();",
    "      }",
    "      /* 帧里实时读颜色，所以换配色通常不用重建；重建过的资源交给 fxPalette 处理 */",
    "      if (reset) setup();",
    "      else if (typeof fxPalette === \"function\") fxPalette();",
    "    }",
    "  });",
    "",
    "  var resizeTimer = 0;",
    "  window.addEventListener(\"resize\", function () {",
    "    clearTimeout(resizeTimer);",
    "    resizeTimer = setTimeout(setup, 140);",
    "  });",
    "",
    "  /* ================= 效果实现 ================= */",
    "",
    def.script,
    "",
    "  /* ================= 启动 ================= */",
    "  setup();",
    "  /* 先同步画一帧，避免首帧空白 */",
    "  FX.frames = 1;",
    "  if (typeof fxFrame === \"function\") fxFrame(0);",
    "  requestAnimationFrame(loop);",
    "})();",
  ].join("\n")

  return [
    "<!doctype html>",
    '<html lang="zh-CN">',
    "<head>",
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    '<meta name="theme-color" content="' + (PALETTES[opt.palette] || PALETTES[0]).bg + '" />',
    "<title>" + def.name + " · BitLeap 特效</title>",
    "<style>",
    BASE_CSS,
    "</style>",
    "</head>",
    "<body>",
    '<canvas id="fx"></canvas>',
    "<script>",
    runtime,
    "</scr" + "ipt>",
    "</body>",
    "</html>",
    "",
  ].join("\n")
}

/* ============================ 效果实现 ============================ */

export const EFFECTS: EffectDef[] = [
  {
    id: "starfield",
    name: "星空穿越",
    desc: "3D 星点向屏幕飞入，带透视拖尾，鼠标位置就是消失点。",
    category: "particle",
    tags: ["Canvas 2D", "透视投影", "拖尾"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var stars = [];",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  var n = Math.round(360 * FX.opt.density * FX.k);",
      "  stars = [];",
      "  for (var i = 0; i < n; i++) stars.push({",
      "    x: Math.random() * 2 - 1,",
      "    y: Math.random() * 2 - 1,",
      "    z: 0.05 + Math.random() * 1.1,",
      "    c: i % 3",
      "  });",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 1;",
      "  ctx.fillStyle = FX.fade(0.24);",
      "  ctx.fillRect(0, 0, W, H);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  var cx = FX.pointer.has ? FX.pointer.x : W * 0.5;",
      "  var cy = FX.pointer.has ? FX.pointer.y : H * 0.5;",
      "  var v = 0.36 * FX.opt.speed;",
      "  for (var i = 0; i < stars.length; i++) {",
      "    var s = stars[i];",
      "    var pz = s.z;",
      "    s.z -= (0.25 + s.z * 0.9) * v * FX.dt;",
      "    if (s.z <= 0.04) {",
      "      s.x = Math.random() * 2 - 1;",
      "      s.y = Math.random() * 2 - 1;",
      "      s.z = 1.15;",
      "      s.c = (Math.random() * 3) | 0;",
      "      continue;",
      "    }",
      "    var k = 0.5 / s.z;",
      "    var x = cx + s.x * k * W * 0.5;",
      "    var y = cy + s.y * k * H * 0.5;",
      "    if (x < -60 || x > W + 60 || y < -60 || y > H + 60) {",
      "      s.x = Math.random() * 2 - 1;",
      "      s.y = Math.random() * 2 - 1;",
      "      s.z = 1.15;",
      "      continue;",
      "    }",
      "    var pk = 0.5 / pz;",
      "    var px = cx + s.x * pk * W * 0.5;",
      "    var py = cy + s.y * pk * H * 0.5;",
      "    var a = Math.min(1, (1.15 - s.z) * 1.5) * 0.9;",
      "    ctx.strokeStyle = FX.color(s.c, a.toFixed(2));",
      "    ctx.lineWidth = Math.max(0.7, (1.2 - s.z) * 2.4);",
      "    ctx.beginPath();",
      "    ctx.moveTo(px, py);",
      "    ctx.lineTo(x, y);",
      "    ctx.stroke();",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    id: "flow",
    name: "流场粒子",
    desc: "几千个粒子沿噪声流场游走，鼠标像一块磁铁把轨迹推开。",
    category: "particle",
    tags: ["Canvas 2D", "噪声流场", "长拖尾"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var parts = [];",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  var n = Math.round(900 * FX.opt.density * FX.k);",
      "  parts = [];",
      "  for (var i = 0; i < n; i++) {",
      "    parts.push({",
      "      x: Math.random() * FX.W,",
      "      y: Math.random() * FX.H,",
      "      px: 0, py: 0,",
      "      age: Math.random() * 240,",
      "      life: 140 + Math.random() * 260,",
      "      c: i % 3,",
      "      w: 0.6 + Math.random() * 1.1",
      "    });",
      "    parts[i].px = parts[i].x;",
      "    parts[i].py = parts[i].y;",
      "  }",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 1;",
      "  ctx.fillStyle = FX.fade(0.055);",
      "  ctx.fillRect(0, 0, W, H);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  var sc = 0.0021;",
      "  var sp = 120 * FX.opt.speed;",
      "  var pr = Math.min(W, H) * 0.26;",
      "  var pr2 = pr * pr;",
      "  for (var i = 0; i < parts.length; i++) {",
      "    var p = parts[i];",
      "    var ang = FX.noise2(p.x * sc + t * 0.11, p.y * sc - t * 0.07) * 12.566;",
      "    var vx = Math.cos(ang), vy = Math.sin(ang);",
      "    if (FX.pointer.has) {",
      "      var dx = p.x - FX.pointer.x, dy = p.y - FX.pointer.y;",
      "      var d2 = dx * dx + dy * dy;",
      "      if (d2 < pr2 && d2 > 4) {",
      "        var f = (1 - d2 / pr2) * 2.6 / Math.sqrt(d2);",
      "        vx += dx * f;",
      "        vy += dy * f;",
      "      }",
      "    }",
      "    p.px = p.x;",
      "    p.py = p.y;",
      "    p.x += vx * sp * FX.dt;",
      "    p.y += vy * sp * FX.dt;",
      "    p.age += 1;",
      "    if (p.age > p.life || p.x < -30 || p.x > W + 30 || p.y < -30 || p.y > H + 30) {",
      "      p.x = Math.random() * W;",
      "      p.y = Math.random() * H;",
      "      p.px = p.x;",
      "      p.py = p.y;",
      "      p.age = 0;",
      "      continue;",
      "    }",
      "    var k = 1 - p.age / p.life;",
      "    ctx.strokeStyle = FX.color(p.c, (k * 0.42).toFixed(3));",
      "    ctx.lineWidth = p.w;",
      "    ctx.beginPath();",
      "    ctx.moveTo(p.px, p.py);",
      "    ctx.lineTo(p.x, p.y);",
      "    ctx.stroke();",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    id: "text-morph",
    name: "粒子文字",
    desc: "把字形的像素当成目标点，粒子用弹簧靠过去，鼠标能把它们吹散。",
    category: "particle",
    tags: ["Canvas 2D", "字形采样", "弹簧运动"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var WORDS = [\"BITLEAP\", \"VIBE\", \"粒子\", \"CODE\"];",
      "var dots = [];",
      "var sets = [];",
      "var wordIdx = 0;",
      "var lastSwap = 0;",
      "function sampleWord(word, W, H) {",
      "  var off = document.createElement(\"canvas\");",
      "  off.width = Math.max(1, Math.round(W));",
      "  off.height = Math.max(1, Math.round(H));",
      "  var g = off.getContext(\"2d\");",
      "  if (!g) return [];",
      "  g.fillStyle = \"#fff\";",
      "  g.textAlign = \"center\";",
      "  g.textBaseline = \"middle\";",
      "  var size = Math.min(W * (word.length > 4 ? 0.17 : 0.24), H * 0.38);",
      "  g.font = \"800 \" + Math.round(size) + \"px -apple-system, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', Arial, sans-serif\";",
      "  g.fillText(word, W / 2, H * 0.47);",
      "  var data = g.getImageData(0, 0, off.width, off.height).data;",
      "  var step = W > 1200 ? 6 : (W > 700 ? 5 : 4);",
      "  var pts = [];",
      "  for (var y = 0; y < off.height; y += step) {",
      "    for (var x = 0; x < off.width; x += step) {",
      "      if (data[(y * off.width + x) * 4 + 3] > 128) pts.push(x, y);",
      "    }",
      "  }",
      "  return pts;",
      "}",
      "function assign(idx) {",
      "  var arr = sets[idx];",
      "  /* 采样为空时保持原位，别让取模算出 NaN 把粒子甩飞 */",
      "  if (!arr || arr.length < 2) return;",
      "  var total = arr.length / 2;",
      "  for (var i = 0; i < dots.length; i++) {",
      "    var p = (i % total) * 2;",
      "    dots[i].tx = arr[p];",
      "    dots[i].ty = arr[p + 1];",
      "  }",
      "}",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  var W = FX.W, H = FX.H;",
      "  sets = WORDS.map(function (w) { return sampleWord(w, W, H); });",
      "  var maxPts = 0;",
      "  for (var i = 0; i < sets.length; i++) maxPts = Math.max(maxPts, sets[i].length / 2);",
      "  /* 点太多会糊，按密度截断，并保证至少有一个点可用 */",
      "  var count = Math.max(200, Math.round(Math.min(maxPts, 5200) * Math.min(1.6, FX.opt.density)));",
      "  dots = [];",
      "  for (var j = 0; j < count; j++) {",
      "    dots.push({",
      "      x: Math.random() * W,",
      "      y: Math.random() * H,",
      "      vx: 0, vy: 0, tx: W / 2, ty: H / 2,",
      "      c: j % 3",
      "    });",
      "  }",
      "  wordIdx = 0;",
      "  lastSwap = 0;",
      "  assign(0);",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"destination-out\";",
      "  ctx.globalAlpha = 0.22;",
      "  ctx.fillStyle = \"#000\";",
      "  ctx.fillRect(0, 0, W, H);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  ctx.globalAlpha = 1;",
      "  var pr = Math.min(W, H) * 0.2;",
      "  var pr2 = pr * pr;",
      "  var sp = Math.max(0.2, FX.opt.speed);",
      "  for (var i = 0; i < dots.length; i++) {",
      "    var d = dots[i];",
      "    d.vx += (d.tx - d.x) * 0.010 * sp;",
      "    d.vy += (d.ty - d.y) * 0.010 * sp;",
      "    if (FX.pointer.has) {",
      "      var dx = d.x - FX.pointer.x, dy = d.y - FX.pointer.y;",
      "      var dd = dx * dx + dy * dy;",
      "      if (dd < pr2 && dd > 1) {",
      "        var f = (1 - dd / pr2) * 3.4 / Math.sqrt(dd);",
      "        d.vx += dx * f * sp;",
      "        d.vy += dy * f * sp;",
      "      }",
      "    }",
      "    d.vx *= 0.9;",
      "    d.vy *= 0.9;",
      "    d.x += d.vx;",
      "    d.y += d.vy;",
      "    ctx.fillStyle = FX.color(d.c, 0.85);",
      "    ctx.fillRect(d.x, d.y, 1.9, 1.9);",
      "  }",
      "  if (t - lastSwap > 3.4) {",
      "    lastSwap = t;",
      "    wordIdx = (wordIdx + 1) % WORDS.length;",
      "    assign(wordIdx);",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    id: "orbit",
    name: "星轨环绕",
    desc: "粒子按不同半径分层绕行，圆心的位置跟着鼠标缓动。",
    category: "particle",
    tags: ["Canvas 2D", "轨道运动", "鼠标跟随"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var orbs = [];",
      "var ox = 0, oy = 0, hasCenter = false;",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  var n = Math.round(420 * FX.opt.density * FX.k);",
      "  orbs = [];",
      "  for (var i = 0; i < n; i++) {",
      "    var ring = (i % 5) + 1;",
      "    orbs.push({",
      "      r: ring * (0.055 + Math.random() * 0.028),",
      "      a: Math.random() * 6.2832,",
      "      sp: (0.35 + Math.random() * 0.7) / ring * (i % 2 ? 1 : -1),",
      "      s: 0.5 + Math.random() * 1.5,",
      "      c: i % 3",
      "    });",
      "  }",
      "  hasCenter = false;",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 1;",
      "  ctx.fillStyle = FX.fade(0.14);",
      "  ctx.fillRect(0, 0, W, H);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  var tx = FX.pointer.has ? FX.pointer.x : W * 0.5;",
      "  var ty = FX.pointer.has ? FX.pointer.y : H * 0.5;",
      "  if (!hasCenter) { ox = tx; oy = ty; hasCenter = true; }",
      "  ox += (tx - ox) * 0.045;",
      "  oy += (ty - oy) * 0.045;",
      "  var base = Math.min(W, H) * 0.46;",
      "  var sp = FX.opt.speed;",
      "  for (var i = 0; i < orbs.length; i++) {",
      "    var o = orbs[i];",
      "    o.a += o.sp * sp * FX.dt;",
      "    var rr = o.r * base * (1 + 0.09 * Math.sin(t * 0.7 + i * 0.05));",
      "    var x = ox + Math.cos(o.a) * rr;",
      "    var y = oy + Math.sin(o.a) * rr * 0.74;",
      "    ctx.fillStyle = FX.color(o.c, 0.7);",
      "    ctx.beginPath();",
      "    ctx.arc(x, y, o.s, 0, 6.2832);",
      "    ctx.fill();",
      "  }",
      "  ctx.fillStyle = FX.color(2, 0.5);",
      "  ctx.beginPath();",
      "  ctx.arc(ox, oy, 2.4, 0, 6.2832);",
      "  ctx.fill();",
      "}",
    ].join("\n"),
  },
  {
    id: "fireflies",
    name: "萤火微光",
    desc: "柔光精灵图叠加成呼吸的萤火，鼠标附近的光点会被吸过来。",
    category: "particle",
    tags: ["Canvas 2D", "精灵图", "呼吸光效"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var flies = [];",
      "var sprites = [];",
      "function makeSprite(rgb) {",
      "  var s = document.createElement(\"canvas\");",
      "  s.width = 64; s.height = 64;",
      "  var g = s.getContext(\"2d\");",
      "  var grd = g.createRadialGradient(32, 32, 0, 32, 32, 32);",
      "  grd.addColorStop(0, \"rgba(\" + rgb[0] + \",\" + rgb[1] + \",\" + rgb[2] + \",1)\");",
      "  grd.addColorStop(0.22, \"rgba(\" + rgb[0] + \",\" + rgb[1] + \",\" + rgb[2] + \",0.5)\");",
      "  grd.addColorStop(1, \"rgba(\" + rgb[0] + \",\" + rgb[1] + \",\" + rgb[2] + \",0)\");",
      "  g.fillStyle = grd;",
      "  g.fillRect(0, 0, 64, 64);",
      "  return s;",
      "}",
      "function fxPalette() {",
      "  sprites = FX.colorsRGB.map(makeSprite);",
      "}",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  var n = Math.round(120 * FX.opt.density * FX.k);",
      "  flies = [];",
      "  for (var i = 0; i < n; i++) {",
      "    flies.push({",
      "      x: Math.random() * FX.W,",
      "      y: Math.random() * FX.H,",
      "      vx: (Math.random() - 0.5) * 10,",
      "      vy: (Math.random() - 0.5) * 10,",
      "      ph: Math.random() * 6.2832,",
      "      ps: 0.5 + Math.random() * 1.4,",
      "      sz: (18 + Math.random() * 54) * FX.scale,",
      "      c: i % 3",
      "    });",
      "  }",
      "  fxPalette();",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 0.14;",
      "  ctx.fillStyle = FX.bgHex;",
      "  ctx.fillRect(0, 0, W, H);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  var sp = FX.opt.speed;",
      "  for (var i = 0; i < flies.length; i++) {",
      "    var f = flies[i];",
      "    var ang = FX.noise2(f.x * 0.0016 + t * 0.06, f.y * 0.0016) * 12.566;",
      "    f.vx += Math.cos(ang) * 30 * FX.dt;",
      "    f.vy += Math.sin(ang) * 30 * FX.dt;",
      "    if (FX.pointer.has) {",
      "      var dx = FX.pointer.x - f.x, dy = FX.pointer.y - f.y;",
      "      var d2 = dx * dx + dy * dy;",
      "      if (d2 < 90000 && d2 > 100) {",
      "        var k = 42 / Math.sqrt(d2);",
      "        f.vx += dx * k * FX.dt;",
      "        f.vy += dy * k * FX.dt;",
      "      }",
      "    }",
      "    f.vx *= 0.988;",
      "    f.vy *= 0.988;",
      "    f.x += f.vx * sp * FX.dt;",
      "    f.y += f.vy * sp * FX.dt;",
      "    if (f.x < -70) f.x = W + 70;",
      "    if (f.x > W + 70) f.x = -70;",
      "    if (f.y < -70) f.y = H + 70;",
      "    if (f.y > H + 70) f.y = -70;",
      "    var pulse = 0.45 + 0.55 * (0.5 + 0.5 * Math.sin(t * f.ps + f.ph));",
      "    var size = f.sz * (0.8 + 0.35 * pulse);",
      "    ctx.globalAlpha = pulse * 0.85;",
      "    var spr = sprites[f.c] || sprites[0];",
      "    if (spr) ctx.drawImage(spr, f.x - size / 2, f.y - size / 2, size, size);",
      "  }",
      "  ctx.globalAlpha = 1;",
      "}",
    ].join("\n"),
  },
  {
    id: "net",
    name: "星座网络",
    desc: "漂浮的节点彼此连线，离得越近线越亮，鼠标会牵动附近的节点。",
    category: "particle",
    tags: ["Canvas 2D", "邻近连线", "鼠标牵引"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var nodes = [];",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  /* 连线是 O(n^2)，节点数必须压住 */",
      "  var n = Math.min(150, Math.round(70 * FX.opt.density * FX.k) + 10);",
      "  nodes = [];",
      "  for (var i = 0; i < n; i++) {",
      "    nodes.push({",
      "      x: Math.random() * FX.W,",
      "      y: Math.random() * FX.H,",
      "      vx: (Math.random() - 0.5) * 34,",
      "      vy: (Math.random() - 0.5) * 34,",
      "      r: 0.8 + Math.random() * 1.7,",
      "      c: i % 3",
      "    });",
      "  }",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 0.32;",
      "  ctx.fillStyle = FX.bgHex;",
      "  ctx.fillRect(0, 0, W, H);",
      "  var sp = FX.opt.speed;",
      "  var i, j, a, b;",
      "  for (i = 0; i < nodes.length; i++) {",
      "    a = nodes[i];",
      "    if (FX.pointer.has) {",
      "      var dx = FX.pointer.x - a.x, dy = FX.pointer.y - a.y;",
      "      var d2 = dx * dx + dy * dy;",
      "      if (d2 < 160000 && d2 > 400) {",
      "        var k = 16 / Math.sqrt(d2);",
      "        a.vx += dx * k * FX.dt;",
      "        a.vy += dy * k * FX.dt;",
      "      }",
      "    }",
      "    a.x += a.vx * sp * FX.dt;",
      "    a.y += a.vy * sp * FX.dt;",
      "    if (a.x < 0) { a.x = 0; a.vx = Math.abs(a.vx); }",
      "    if (a.x > W) { a.x = W; a.vx = -Math.abs(a.vx); }",
      "    if (a.y < 0) { a.y = 0; a.vy = Math.abs(a.vy); }",
      "    if (a.y > H) { a.y = H; a.vy = -Math.abs(a.vy); }",
      "    a.vx *= 0.996;",
      "    a.vy *= 0.996;",
      "  }",
      "  var link = Math.min(W, H) * 0.34;",
      "  var link2 = link * link;",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  ctx.globalAlpha = 1;",
      "  ctx.lineWidth = 1;",
      "  for (i = 0; i < nodes.length; i++) {",
      "    a = nodes[i];",
      "    for (j = i + 1; j < nodes.length; j++) {",
      "      b = nodes[j];",
      "      var lx = a.x - b.x, ly = a.y - b.y;",
      "      var l2 = lx * lx + ly * ly;",
      "      if (l2 > link2) continue;",
      "      ctx.strokeStyle = FX.color(a.c, ((1 - l2 / link2) * 0.34).toFixed(3));",
      "      ctx.beginPath();",
      "      ctx.moveTo(a.x, a.y);",
      "      ctx.lineTo(b.x, b.y);",
      "      ctx.stroke();",
      "    }",
      "  }",
      "  for (i = 0; i < nodes.length; i++) {",
      "    a = nodes[i];",
      "    ctx.fillStyle = FX.color(a.c, 0.9);",
      "    ctx.beginPath();",
      "    ctx.arc(a.x, a.y, a.r, 0, 6.2832);",
      "    ctx.fill();",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    id: "aurora",
    name: "极光星云",
    desc: "片元着色器里叠五层噪声再做域扭曲，鼠标会改变扭曲方向。",
    category: "background",
    tags: ["WebGL", "域扭曲噪声", "fbm"],
    controls: ["speed", "palette"],
    defaults: { speed: 1 },
    script: [
      "var gl = null, program = null, uni = {}, quad = null;",
      "function compile(type, src) {",
      "  var sh = gl.createShader(type);",
      "  gl.shaderSource(sh, src);",
      "  gl.compileShader(sh);",
      "  if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {",
      "    if (window.console) console.error(gl.getShaderInfoLog(sh));",
      "    return null;",
      "  }",
      "  return sh;",
      "}",
      "function fxSetup() {",
      "  var canvas = FX.canvas;",
      "  /* preserveDrawingBuffer 让画布可以被 readPixels 或右键另存为图片 */",
      "  gl = canvas.getContext(\"webgl\", { antialias: false, alpha: false, preserveDrawingBuffer: true }) || canvas.getContext(\"experimental-webgl\");",
      "  if (!gl) return;",
      "  gl.viewport(0, 0, canvas.width, canvas.height);",
      "  if (program) { return; }",
      "  var VS = [",
      "    \"attribute vec2 aPos;\",",
      "    \"void main(){ gl_Position = vec4(aPos, 0.0, 1.0); }\"",
      "  ].join(\"\\n\");",
      "  var FS = [",
      "    \"precision highp float;\",",
      "    \"uniform vec2 uRes; uniform float uTime; uniform vec2 uPointer;\",",
      "    \"uniform vec3 uC1; uniform vec3 uC2; uniform vec3 uC3; uniform vec3 uC4;\",",
      "    \"float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123); }\",",
      "    \"float noise(vec2 p){ vec2 i = floor(p); vec2 f = fract(p); vec2 u = f * f * (3.0 - 2.0 * f);\",",
      "    \"  return mix(mix(hash(i), hash(i + vec2(1.0, 0.0)), u.x), mix(hash(i + vec2(0.0, 1.0)), hash(i + vec2(1.0, 1.0)), u.x), u.y); }\",",
      "    \"float fbm(vec2 p){ float v = 0.0; float a = 0.5; for (int i = 0; i < 5; i++) { v += a * noise(p); p *= 2.03; a *= 0.5; } return v; }\",",
      "    \"void main(){\",",
      "    \"  float m = min(uRes.x, uRes.y);\",",
      "    \"  vec2 uv = gl_FragCoord.xy / uRes.xy;\",",
      "    \"  vec2 p = (gl_FragCoord.xy - 0.5 * uRes.xy) / m;\",",
      "    \"  vec2 mouse = (uPointer - 0.5) * (uRes / m) * 0.55;\",",
      "    \"  float t = uTime * 0.14;\",",
      "    \"  vec2 q = vec2(fbm(p * 3.4 + t), fbm(p * 3.4 + vec2(5.2, 1.3) - t));\",",
      "    \"  vec2 r = vec2(fbm(p * 4.4 + 2.2 * q + vec2(1.7, 9.2) + 0.18 * mouse), fbm(p * 4.4 + 2.2 * q + vec2(8.3, 2.8) - 0.18 * mouse));\",",
      "    \"  float f = fbm(p * 1.7 + 2.0 * r);\",",
      "    \"  float fn = clamp((f + 0.28 * r.x - 0.30) / 0.42, 0.0, 1.0);\",",
      "    \"  vec3 col = uC1;\",",
      "    \"  col = mix(col, uC2, smoothstep(0.02, 0.70, fn));\",",
      "    \"  col = mix(col, uC3, smoothstep(0.45, 0.95, fn));\",",
      "    \"  col = mix(col, uC4, min(smoothstep(0.74, 1.00, fn) * 1.05, 1.0));\",",
      "    \"  col *= 1.25;\",",
      "    \"  col *= 1.0 - 0.62 * smoothstep(0.25, 1.05, distance(uv, vec2(0.5, 1.18)));\",",
      "    \"  col *= 1.0 - 0.34 * pow(clamp(length(uv - 0.5) * 1.32, 0.0, 1.0), 2.2);\",",
      "    \"  col += (hash(gl_FragCoord.xy + fract(uTime)) - 0.5) * 0.022;\",",
      "    \"  gl_FragColor = vec4(col, 1.0);\",",
      "    \"}\"",
      "  ].join(\"\\n\");",
      "  var vs = compile(gl.VERTEX_SHADER, VS);",
      "  var fs = compile(gl.FRAGMENT_SHADER, FS);",
      "  if (!vs || !fs) return;",
      "  program = gl.createProgram();",
      "  gl.attachShader(program, vs);",
      "  gl.attachShader(program, fs);",
      "  gl.linkProgram(program);",
      "  if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {",
      "    if (window.console) console.error(gl.getProgramInfoLog(program));",
      "    program = null;",
      "    return;",
      "  }",
      "  gl.useProgram(program);",
      "  quad = gl.createBuffer();",
      "  gl.bindBuffer(gl.ARRAY_BUFFER, quad);",
      "  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);",
      "  var loc = gl.getAttribLocation(program, \"aPos\");",
      "  gl.enableVertexAttribArray(loc);",
      "  gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);",
      "  uni.res = gl.getUniformLocation(program, \"uRes\");",
      "  uni.time = gl.getUniformLocation(program, \"uTime\");",
      "  uni.ptr = gl.getUniformLocation(program, \"uPointer\");",
      "  uni.c = [",
      "    gl.getUniformLocation(program, \"uC1\"),",
      "    gl.getUniformLocation(program, \"uC2\"),",
      "    gl.getUniformLocation(program, \"uC3\"),",
      "    gl.getUniformLocation(program, \"uC4\")",
      "  ];",
      "}",
      "function fxFrame(t) {",
      "  if (!gl || !program) return;",
      "  var c = FX.canvas;",
      "  gl.viewport(0, 0, c.width, c.height);",
      "  gl.uniform2f(uni.res, c.width, c.height);",
      "  gl.uniform1f(uni.time, t * FX.opt.speed);",
      "  gl.uniform2f(uni.ptr, FX.pointer.has ? FX.nx() : 0.5, FX.pointer.has ? FX.ny() : 0.5);",
      "  /* 底色 + 配色三色，正好对上着色器里的四层颜色 */",
      "  var pal = [FX.bgRGB].concat(FX.colorsRGB);",
      "  for (var i = 0; i < 4; i++) {",
      "    var v = pal[i] || pal[0];",
      "    gl.uniform3f(uni.c[i], v[0] / 255, v[1] / 255, v[2] / 255);",
      "  }",
      "  gl.drawArrays(gl.TRIANGLES, 0, 3);",
      "}",
    ].join("\n"),
  },
  {
    id: "ripple",
    name: "液态波纹",
    desc: "多组正弦波相互干涉出液态质感，指针附近会隆起一圈涟漪。",
    category: "background",
    tags: ["WebGL", "波干涉", "指针涟漪"],
    controls: ["speed", "palette"],
    defaults: { speed: 1 },
    script: [
      "var gl = null, program = null, uni = {};",
      "function compile(type, src) {",
      "  var sh = gl.createShader(type);",
      "  gl.shaderSource(sh, src);",
      "  gl.compileShader(sh);",
      "  if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {",
      "    if (window.console) console.error(gl.getShaderInfoLog(sh));",
      "    return null;",
      "  }",
      "  return sh;",
      "}",
      "function fxSetup() {",
      "  var canvas = FX.canvas;",
      "  /* preserveDrawingBuffer 让画布可以被 readPixels 或右键另存为图片 */",
      "  gl = canvas.getContext(\"webgl\", { antialias: false, alpha: false, preserveDrawingBuffer: true }) || canvas.getContext(\"experimental-webgl\");",
      "  if (!gl) return;",
      "  gl.viewport(0, 0, canvas.width, canvas.height);",
      "  if (program) return;",
      "  var VS = \"attribute vec2 aPos; void main(){ gl_Position = vec4(aPos, 0.0, 1.0); }\";",
      "  var FS = [",
      "    \"precision highp float;\",",
      "    \"uniform vec2 uRes; uniform float uTime; uniform vec2 uPointer;\",",
      "    \"uniform vec3 uBg; uniform vec3 uC1; uniform vec3 uC2; uniform vec3 uC3;\",",
      "    \"void main(){\",",
      "    \"  vec2 uv = gl_FragCoord.xy / uRes.xy;\",",
      "    \"  float m = min(uRes.x, uRes.y);\",",
      "    \"  vec2 p = (gl_FragCoord.xy - 0.5 * uRes.xy) / m;\",",
      "    \"  vec2 mp = (uPointer * uRes - 0.5 * uRes.xy) / m;\",",
      "    \"  float d = length(p);\",",
      "    \"  float t = uTime;\",",
      "    \"  float w = sin(d * 24.0 - t * 1.7) * 0.5;\",",
      "    \"  w += sin((p.x * 1.6 + p.y) * 11.0 + t * 1.1) * 0.34;\",",
      "    \"  w += sin((p.x - p.y * 1.4) * 14.0 - t * 0.9) * 0.30;\",",
      "    \"  w += sin(d * 52.0 - t * 2.5) * 0.16;\",",
      "    \"  float ring = length(p - mp);\",",
      "    \"  w += sin(ring * 46.0 - t * 3.2) * 0.30 * exp(-ring * 4.2);\",",
      "    \"  w = clamp(w * 0.5 + 0.5, 0.0, 1.0);\",",
      "    \"  vec3 col = mix(uBg, uC1, smoothstep(0.14, 0.72, w));\",",
      "    \"  col = mix(col, uC2, pow(w, 3.0) * 0.95);\",",
      "    \"  col = mix(col, uC3, pow(w, 7.0) * 0.85);\",",
      "    \"  col += uC3 * exp(-ring * 9.0) * 0.22;\",",
      "    \"  col *= 1.0 - 0.45 * pow(clamp(d * 0.95, 0.0, 1.0), 2.0);\",",
      "    \"  gl_FragColor = vec4(col, 1.0);\",",
      "    \"}\"",
      "  ].join(\"\\n\");",
      "  var vs = compile(gl.VERTEX_SHADER, VS);",
      "  var fs = compile(gl.FRAGMENT_SHADER, FS);",
      "  if (!vs || !fs) return;",
      "  program = gl.createProgram();",
      "  gl.attachShader(program, vs);",
      "  gl.attachShader(program, fs);",
      "  gl.linkProgram(program);",
      "  if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {",
      "    if (window.console) console.error(gl.getProgramInfoLog(program));",
      "    program = null;",
      "    return;",
      "  }",
      "  gl.useProgram(program);",
      "  var buf = gl.createBuffer();",
      "  gl.bindBuffer(gl.ARRAY_BUFFER, buf);",
      "  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);",
      "  var loc = gl.getAttribLocation(program, \"aPos\");",
      "  gl.enableVertexAttribArray(loc);",
      "  gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);",
      "  uni.res = gl.getUniformLocation(program, \"uRes\");",
      "  uni.time = gl.getUniformLocation(program, \"uTime\");",
      "  uni.ptr = gl.getUniformLocation(program, \"uPointer\");",
      "  uni.bg = gl.getUniformLocation(program, \"uBg\");",
      "  uni.c = [",
      "    gl.getUniformLocation(program, \"uC1\"),",
      "    gl.getUniformLocation(program, \"uC2\"),",
      "    gl.getUniformLocation(program, \"uC3\")",
      "  ];",
      "}",
      "function fxFrame(t) {",
      "  if (!gl || !program) return;",
      "  var c = FX.canvas;",
      "  gl.viewport(0, 0, c.width, c.height);",
      "  gl.uniform2f(uni.res, c.width, c.height);",
      "  gl.uniform1f(uni.time, t * FX.opt.speed);",
      "  gl.uniform2f(uni.ptr, FX.pointer.has ? FX.nx() : 0.5, FX.pointer.has ? FX.ny() : 0.5);",
      "  var bg = FX.bgRGB;",
      "  gl.uniform3f(uni.bg, bg[0] / 255, bg[1] / 255, bg[2] / 255);",
      "  for (var i = 0; i < 3; i++) {",
      "    var v = FX.colorsRGB[i] || bg;",
      "    gl.uniform3f(uni.c[i], v[0] / 255, v[1] / 255, v[2] / 255);",
      "  }",
      "  gl.drawArrays(gl.TRIANGLES, 0, 3);",
      "}",
    ].join("\n"),
  },
  {
    id: "mesh",
    name: "流动光斑",
    desc: "几团大光斑缓慢漂浮相互叠加，是最省电的那种氛围背景。",
    category: "background",
    tags: ["Canvas 2D", "径向渐变", "叠加混色"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var blobs = [];",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  var n = Math.max(3, Math.round(5 * FX.opt.density));",
      "  blobs = [];",
      "  for (var i = 0; i < n; i++) {",
      "    blobs.push({",
      "      x: Math.random(),",
      "      y: Math.random(),",
      "      vx: (Math.random() - 0.5) * 0.055,",
      "      vy: (Math.random() - 0.5) * 0.055,",
      "      r: 0.32 + Math.random() * 0.28,",
      "      c: i % 3",
      "    });",
      "  }",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 1;",
      "  ctx.fillStyle = FX.bgHex;",
      "  ctx.fillRect(0, 0, W, H);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  var big = Math.max(W, H);",
      "  var sp = FX.opt.speed;",
      "  for (var i = 0; i < blobs.length; i++) {",
      "    var b = blobs[i];",
      "    b.x += b.vx * sp * FX.dt;",
      "    b.y += b.vy * sp * FX.dt;",
      "    if (b.x < -0.25 || b.x > 1.25) b.vx = -b.vx;",
      "    if (b.y < -0.25 || b.y > 1.25) b.vy = -b.vy;",
      "    var x = b.x * W, y = b.y * H;",
      "    var rad = b.r * big * 0.85;",
      "    var grd = ctx.createRadialGradient(x, y, 0, x, y, rad);",
      "    var c = FX.colorsRGB[b.c] || FX.colorsRGB[0];",
      "    grd.addColorStop(0, \"rgba(\" + c[0] + \",\" + c[1] + \",\" + c[2] + \",0.5)\");",
      "    grd.addColorStop(0.55, \"rgba(\" + c[0] + \",\" + c[1] + \",\" + c[2] + \",0.16)\");",
      "    grd.addColorStop(1, \"rgba(\" + c[0] + \",\" + c[1] + \",\" + c[2] + \",0)\");",
      "    ctx.fillStyle = grd;",
      "    ctx.fillRect(x - rad, y - rad, rad * 2, rad * 2);",
      "  }",
      "  if (FX.pointer.has) {",
      "    var mx = FX.pointer.x, my = FX.pointer.y;",
      "    var mr = Math.min(W, H) * 0.3;",
      "    var g2 = ctx.createRadialGradient(mx, my, 0, mx, my, mr);",
      "    var c2 = FX.colorsRGB[2] || FX.colorsRGB[0];",
      "    g2.addColorStop(0, \"rgba(\" + c2[0] + \",\" + c2[1] + \",\" + c2[2] + \",0.22)\");",
      "    g2.addColorStop(1, \"rgba(\" + c2[0] + \",\" + c2[1] + \",\" + c2[2] + \",0)\");",
      "    ctx.fillStyle = g2;",
      "    ctx.fillRect(mx - mr, my - mr, mr * 2, mr * 2);",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    id: "horizon",
    name: "赛博网格",
    desc: "透视网格向着地平线收束并不断后退，适合做科技感的页头。",
    category: "background",
    tags: ["Canvas 2D", "透视网格", "Retro"],
    controls: ["speed", "palette"],
    defaults: { speed: 1 },
    script: [
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 1;",
      "  var hy = Math.round(H * 0.54);",
      "  /* 天空：从底色渐变到第一配色 */",
      "  var sky = ctx.createLinearGradient(0, 0, 0, hy);",
      "  sky.addColorStop(0, FX.bgHex);",
      "  sky.addColorStop(1, FX.color(1, 0.34));",
      "  ctx.fillStyle = sky;",
      "  ctx.fillRect(0, 0, W, hy);",
      "  ctx.fillStyle = FX.bgHex;",
      "  ctx.fillRect(0, hy, W, H - hy);",
      "  /* 地平线上的光晕 */",
      "  var cx = W * 0.5;",
      "  var sr = Math.min(W, H) * 0.26;",
      "  var glow = ctx.createRadialGradient(cx, hy - sr * 0.35, 0, cx, hy - sr * 0.35, sr);",
      "  glow.addColorStop(0, FX.color(2, 0.85));",
      "  glow.addColorStop(0.45, FX.color(0, 0.34));",
      "  glow.addColorStop(1, FX.color(0, 0));",
      "  ctx.fillStyle = glow;",
      "  ctx.fillRect(0, 0, W, hy);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  /* 横线：近处疏、远处密 */",
      "  var off = (t * FX.opt.speed * 0.32) % 1;",
      "  ctx.lineWidth = 1;",
      "  for (var i = 0; i < 30; i++) {",
      "    var z = (i + off) / 30;",
      "    if (z <= 0.001) continue;",
      "    var p = Math.pow(z, 2.4);",
      "    var y = hy + (H - hy) * p;",
      "    if (y > H + 2) continue;",
      "    ctx.globalAlpha = Math.min(1, p * 3.2) * 0.55;",
      "    ctx.strokeStyle = FX.color(0, 1);",
      "    ctx.beginPath();",
      "    ctx.moveTo(0, y);",
      "    ctx.lineTo(W, y);",
      "    ctx.stroke();",
      "  }",
      "  /* 竖线：全部汇聚到灭点 */",
      "  ctx.globalAlpha = 0.3;",
      "  ctx.strokeStyle = FX.color(0, 1);",
      "  for (var j = -14; j <= 14; j++) {",
      "    ctx.beginPath();",
      "    ctx.moveTo(cx, hy);",
      "    ctx.lineTo(cx + j * (W / 5.5), H + 60);",
      "    ctx.stroke();",
      "  }",
      "  /* 地平线 */",
      "  ctx.globalAlpha = 0.85;",
      "  ctx.strokeStyle = FX.color(2, 1);",
      "  ctx.lineWidth = 1.6;",
      "  ctx.beginPath();",
      "  ctx.moveTo(0, hy + 0.5);",
      "  ctx.lineTo(W, hy + 0.5);",
      "  ctx.stroke();",
      "  ctx.globalAlpha = 1;",
      "}",
    ].join("\n"),
  },
  {
    id: "vortex",
    name: "漩涡星尘",
    desc: "粒子被卷入缓慢旋转的漩涡，越靠近中心转得越快。",
    category: "particle",
    tags: ["Canvas 2D", "极坐标", "鼠标扰动"],
    controls: ["speed", "density", "palette"],
    defaults: { speed: 1, density: 1 },
    script: [
      "var dust = [];",
      "function fxSetup() {",
      '  FX.ctx = FX.canvas.getContext("2d");',
      "  FX.ctx.setTransform(FX.dpr, 0, 0, FX.dpr, 0, 0);",
      "  var n = Math.round(800 * FX.opt.density * FX.k);",
      "  dust = [];",
      "  for (var i = 0; i < n; i++) {",
      "    dust.push({",
      "      a: Math.random() * 6.2832,",
      "      r: 0.06 + Math.random() * 0.62,",
      "      s: 0.5 + Math.random() * 1.6,",
      "      w: 0.7 + Math.random() * 0.9,",
      "      c: i % 3",
      "    });",
      "  }",
      "}",
      "function fxFrame(t) {",
      "  var ctx = FX.ctx, W = FX.W, H = FX.H;",
      "  if (!ctx) return;",
      "  ctx.globalCompositeOperation = \"source-over\";",
      "  ctx.globalAlpha = 1;",
      "  ctx.fillStyle = FX.fade(0.1);",
      "  ctx.fillRect(0, 0, W, H);",
      "  ctx.globalCompositeOperation = \"lighter\";",
      "  var cx = W * 0.5, cy = H * 0.5;",
      "  var base = Math.min(W, H) * 0.55;",
      "  var sp = FX.opt.speed;",
      "  var pr = Math.min(W, H) * 0.22;",
      "  var pr2 = pr * pr;",
      "  for (var i = 0; i < dust.length; i++) {",
      "    var d = dust[i];",
      "    /* 越靠内圈角速度越大，形成漩涡 */",
      "    d.a += d.w / Math.max(0.12, d.r) * 0.5 * sp * FX.dt;",
      "    var x = cx + Math.cos(d.a) * d.r * base;",
      "    var y = cy + Math.sin(d.a) * d.r * base * 0.86;",
      "    if (FX.pointer.has) {",
      "      var dx = x - FX.pointer.x, dy = y - FX.pointer.y;",
      "      var dd = dx * dx + dy * dy;",
      "      if (dd < pr2 && dd > 1) {",
      "        var f = (1 - dd / pr2) * 0.16;",
      "        x += dx * f;",
      "        y += dy * f;",
      "      }",
      "    }",
      "    ctx.fillStyle = FX.color(d.c, 0.62 - d.r * 0.5);",
      "    ctx.beginPath();",
      "    ctx.arc(x, y, d.s, 0, 6.2832);",
      "    ctx.fill();",
      "  }",
      "}",
    ].join("\n"),
  },
]
