export type Tool = {
  id: string
  title: string
  description: string
  href: string
  icon: string
  category: string
  target?: "_blank"
}

export const tools: Tool[] = [
  { id: 'json', title: 'JSON 格式化', description: 'JSON 美化、压缩、语法校验', href: '/tools/json', icon: 'Braces', category: '文本工具' },
  { id: 'timestamp', title: '时间戳转换', description: 'Unix 时间戳与可读时间互转，支持秒/毫秒', href: '/tools/timestamp', icon: 'Clock', category: '文本工具' },
  { id: 'base64', title: 'Base64 编解码', description: '文本与 Base64 互转', href: '/tools/base64', icon: 'Lock', category: '文本工具' },
  { id: 'url', title: 'URL 编解码', description: 'URL 参数编码与解码', href: '/tools/url', icon: 'Link2', category: '文本工具' },
  { id: 'counter', title: '字数统计', description: '实时统计字符数、字数、阅读时长', href: '/tools/counter', icon: 'Hash', category: '文本工具' },
  { id: 'color', title: '颜色转换', description: 'HEX、RGB、HSL 互转', href: '/tools/color', icon: 'Palette', category: '开发辅助' },
  { id: 'gradient', title: '渐变色生成器', description: '可视化生成 CSS 渐变，支持线性 / 径向渐变', href: '/tools/gradient', icon: 'Blend', category: '开发辅助' },
  { id: 'color-palette', title: '常用配色推荐', description: '精选品牌配色与渐变色，一键应用到你的项目', href: '/tools/color-palette', icon: 'SwatchBook', category: '开发辅助' },
  { id: 'qrcode', title: '二维码生成', description: '将 URL、文本、WiFi 等信息生成二维码，支持 PNG / SVG 下载', href: '/tools/qrcode', icon: 'QrCode', category: '开发辅助' },
  { id: 'api-directory', title: '常用 API', description: '前端可直连的公开 API 索引', href: '/tools/api-directory', icon: 'Plug', category: '灵感与API' },
  { id: 'box-shadow', title: 'Box Shadow 生成器', description: '可视化生成 CSS 盒阴影，支持多层阴影与内阴影', href: '/tools/box-shadow', icon: 'Box', category: 'CSS 工具' },
  { id: 'glow-background', title: '渐变光晕背景', description: '生成带光晕效果的渐变背景，适合卡片与 Banner', href: '/tools/glow-background', icon: 'Sparkles', category: 'CSS 工具' },
  { id: 'flex-grid', title: 'Flex/Grid 布局', description: 'Flex/Grid 布局可视化生成器', href: '/tools/flex-grid', icon: 'LayoutGrid', category: 'CSS 工具' },
  { id: 'uuid', title: 'UUID 生成器', description: '在线生成UUID', href: '/tools/uuid', icon: 'Hash', category: '文本工具' },  
  { id: 'cron', title: 'Cron 表达式生成器', description: '可视化生成定时任务表达式', href: '/tools/cron', icon: 'Timer', category: '开发辅助' },
  { id: 'image-compress', title: '图片压缩', description: '在浏览器中压缩 JPG / PNG / WebP', href: '/tools/image-compress', icon: 'ImageDown', category: '媒体工具' },
  { id: 'regex', title: '正则表达式生成器', description: '通过可视化配置生成常用正则表达式', href: '/tools/regex', icon: 'Regex', category: '开发辅助' },
  { id: 'websocket', title: 'WebSocket 测试台', description: '连接 ws/wss 服务，实时收发消息', href: '/tools/websocket', icon: 'RadioTower', category: '开发辅助' },
  { id: 'pdf-to-word', title: 'PDF 转 Word', description: '提取 PDF 文本内容，生成可编辑的 Word 文档', href: '/tools/pdf-to-word', icon: 'FileText', category: '文本工具' },
  { id: 'fish-screen', title: '摸鱼屏生成器', description: '全屏"系统同步中"进度界面，纯本地模拟', icon: 'Fish', category: '趣味工具', href: '/tools/fish-screen' },
  { id: 'snake', title: '贪吃蛇', description: '经典 Canvas 贪吃蛇，本地最高分', icon: 'Gamepad2', category: '趣味工具', href: '/tools/snake' },
  { id: 'code-rain', title: '代码雨屏保', description: '经典 Matrix 数字雨，可调速换色', icon: 'CloudRain', category: '趣味工具', href: '/tools/code-rain' },
  { id: 'cubic-bezier', title: '缓动曲线预览器', description: '拖控制点看 cubic-bezier 曲线', icon: 'Activity', category: 'CSS 工具', href: '/tools/cubic-bezier' },
  { id: 'clamp', title: 'clamp() 流体计算器', description: '计算流体字号与间距，告别媒体查询', icon: 'Ruler', category: 'CSS 工具', href: '/tools/clamp' },
  { id: 'inspo', title: '开发灵感', description: '收录各种类型的设计站点', href: '/tools/inspo', icon: 'Lightbulb', category: '灵感与API' },
  { id: 'liquid-glass', title: 'Liquid Glass 卡片实验室', description: 'iOS 26 风格毛玻璃，可调可导出', icon: 'GlassWater', category: 'CSS 工具', href: '/tools/liquid-glass' },
  { id: 'test-input', title: '表单校验测试', description: '测试工程师的登录框作弊码', icon: 'ClipboardCheck', category: '测试工具', href: '/tools/test-input' },
  { id: 'HTTP 状态码速查', title: 'HTTP 状态码速查', description: '析参数 · 解码 Payload · 速查状态码', icon: 'SearchCode', category: '测试工具', href: '/tools/url-parser' },
  { id: 'fake-data', title: '数据生成器', description: '带种子的假数据生成器', icon: 'Factory', category: '测试工具', href: '/tools/fake-data' },
  { id: 'clip-path', title: 'clip-path形状生成器', description: 'clip-path形状生成器', icon: 'Diamond', category: 'CSS 工具', href: '/tools/clip-path' },
  { id: 'button-anim', title: 'button按钮动画', description: '常见按钮动画', icon: 'Square', category: 'CSS 工具', href: '/tools/button-anim' },
  { id: 'css-loaders', title: 'CSS 加载动画库', description: '纯 CSS Loader，一键复制', href: '/tools/css-loaders', icon: 'Loader', category: 'CSS 工具' },
  { id: 'img-base64', title: '图片转 Base64', description: '图片转 Data URL，一键复制', href: '/tools/img-base64', icon: 'Image', category: '媒体工具' },
  { id: 'keyboard-tester', title: '键盘按键测试', description: '按下任意键查看 key / code / keyCode', href: '/tools/keyboard-tester', icon: 'Keyboard', category: '趣味工具' },
  { id: 'roulette', title: '随机决定转盘', description: '输入选项，转盘帮你做决定', href: '/tools/roulette', icon: 'Target', category: '趣味工具' },
  { id: 'text-batch', title: '文本去重 & 批量处理', description: '行去重、删除空行、空格清理', href: '/tools/text-batch', icon: 'ListTodo', category: '文本工具' },
  { id: 'text-compare', title: '文本比对查重', description: '两段文本差异高亮对比', href: '/tools/text-compare', icon: 'GitCompare', category: '文本工具' },
  { id: 'pinyin', title: '汉字转拼音', description: '汉字转拼音，支持带声调', href: '/tools/pinyin', icon: 'SpellCheck', category: '文本工具' },
  { id: 'jwt-parser', title: 'JWT 解析器', description: '解析JWT令牌，查看Header、Payload', href: '/tools/jwt-parser', icon: 'Ticket', category: '开发辅助' },
  { id: 'border-radius', title: '边框圆角生成器', description: '可视化调试四角独立圆角', href: '/tools/border-radius', icon: 'SquareRoundCorner', category: 'CSS 工具' },
  { id: 'text-shadow', title: '文字阴影生成器', description: '可视化调试 text-shadow', href: '/tools/text-shadow', icon: 'Type', category: 'CSS 工具' },
  { id: 'image-crop', title: '图片裁剪缩放', description: '浏览器端图片裁剪、修改尺寸', href: '/tools/image-crop', icon: 'Crop', category: '媒体工具' },
  { id: 'image-enhance', title: '图片高清修复', description: '浏览器本地AI超分', href: '/tools/image-enhance', icon: 'ScanSearch', category: '媒体工具' },
  { id: 'hash-calc', title: 'Hash 哈希工具', icon: 'ShieldCheck', description: 'MD5、SHA1、SHA256 本地计算', category: '文本工具', href: '/tools/hash' },
  { id: 'markdown-preview', title: 'Markdown预览', description: 'Markdown实时渲染预览', href: '/tools/markdown-preview', icon: 'FileCode', category: '文本工具' },
  { id: 'yaml-json', title: 'YAML ↔ JSON互转', description: 'YAML与JSON双向转换', href: '/tools/yaml-json', icon: 'ArrowLeftRight', category: '文本工具' },
  { id: 'sql-format', title: 'SQL格式化压缩', description: 'SQL美化排版、压缩', href: '/tools/sql-format', icon: 'Database', category: '文本工具' },
  { id: 'regex-test', title: '正则测试器', description: '输入正则与测试文本，匹配高亮', href: '/tools/regex-test', icon: 'Search', category: '文本工具' },
  { id: 'case-convert', title: '变量命名转换', description: '驼峰、下划线、短横线互转', href: '/tools/case-convert', icon: 'CaseSensitive', category: '文本工具' },
  { id: 'escape-tool', title: '字符串转义工具', description: 'HTML、JS、JSON转义/反转义', href: '/tools/escape', icon: 'TextWrap', category: '文本工具' },
  { id: 'ipv4-calc', title: 'IP子网计算器', description: '输入IP与掩码，计算网段', href: '/tools/ip-calc', icon: 'Network', category: '开发辅助' },
  { id: 'rsa-key', title: 'RSA密钥生成', description: '本地生成RSA公私钥', href: '/tools/rsa-key', icon: 'Key', category: '开发辅助' },
  { id: 'filter-generator', title: 'CSS Filter滤镜生成器', description: '调节亮度对比度模糊', href: '/tools/css-filter', icon: 'Droplet', category: 'CSS 工具' },
  { id: 'transform-generator', title: 'Transform变换工具', description: '旋转缩放倾斜位移调试', href: '/tools/css-transform', icon: 'Move3d', category: 'CSS 工具' },
  { id: 'keyframes-generator', title: 'Keyframes动画生成', description: '可视化关键帧动画', href: '/tools/keyframes', icon: 'Film', category: 'CSS 工具' },
  { id: 'unit-convert', title: 'CSS单位换算', description: 'px rem em vw互相换算', href: '/tools/css-unit', icon: 'Scaling', category: 'CSS 工具' },
  { id: 'image-metadata', title: '图片EXIF查看器', description: '读取图片EXIF元数据', href: '/tools/image-exif', icon: 'Info', category: '媒体工具' },
  { id: 'image-watermark', title: '图片加水印', description: '本地给图片添加文字/图片水印', href: '/tools/image-watermark', icon: 'Stamp', category: '媒体工具' },
  { id: 'format-convert', title: '图片格式转换', description: '图片互转JPG PNG WebP AVIF', href: '/tools/image-convert', icon: 'Repeat', category: '媒体工具' },
  { id: 'mock-server', title: 'Mock接口生成', description: '可视化编写mock接口', href: '/tools/mock', icon: 'Server', category: '测试工具' },
  { id: 'ua-parser', title: 'User‑Agent解析', description: '解析UA字符串', href: '/tools/ua-parser', icon: 'Smartphone', category: '测试工具' },
  { id: 'photopea', title: 'Photopea', description: '在线图片编辑器', icon: 'Image', category: '媒体工具', href: 'https://www.photopea.com', target: '_blank' },
  { id: 'lab', title: '前端实验工作台', description: '浏览器本地实验', href: '/tools/lab', icon: 'FlaskConical', category: '前端实验' },
  { id: 'CssBack', title: 'css液态背景', description: '前端液态气泡背景', href: '/tools/cssback', icon: 'Droplets', category: '前端实验' },
  { id: 'pomodoro', title: '番茄时钟 & 任务看板', description: '番茄计时 + 任务管理', href: '/tools/pomodoro', icon: 'TimerReset', category: '日常工具' },
  { id: 'Echarts', title: 'ECharts 图表生成', description: '粘贴数据，可视化配置图表', href: '/tools/data-visualizer', icon: 'ChartLine', category: '前端实验' },
  { id: 'terminal', title: '终端命令生成器', description: '可视化选择操作，生成终端命令', href: '/tools/terminal', icon: 'Terminal', category: '开发辅助' },
  { id: 'git-cheatsheet', title: 'Git 命令速查', description: '常用 Git 操作一键查询', href: '/tools/git-cheatsheet', icon: 'GitBranch', category: '开发辅助' },
  { id: 'MikuTap', title: '初音节奏', description: '点击屏幕实时合成五声音阶', icon: 'Music', category: '趣味工具', href: 'https://aidn.jp/mikutap/', target: '_blank' },
  { id: 'Hereitis', title: '在这里资源站', description: '免费软件、素材、在线小工具聚合', href: 'https://www.hereitis.cn/', category: '资源导航', target: '_blank', icon: 'FolderOpen' },
  { id: 'LanrenOffice', title: '懒人办公', description: 'PPT/Word/Excel 模板下载', href: 'https://www.lanren.work/', category: '资源导航', target: '_blank', icon: 'Briefcase' },
  { id: 'Neumorphism', title: '软拟态生成器', description: '双向光影软阴影预览', href: 'https://neumorphism.io', icon: 'Layers', category: '资源导航', target: '_blank' },
  { id: 'Patatap', title: 'Patatap', description: '键盘触发几何形状+合成音效', href: 'https://patatap.com', icon: 'Piano', category: '趣味工具', target: '_blank' },
  { id: 'bg-sub', title: 'BgSub 抠图', description: '纯浏览器本地 AI 抠背景', href: 'https://zh.bgsub.com', icon: 'Scissors', category: '媒体工具', target: '_blank' },
  { id: 'table-convert', title: '表格互转', description: 'Markdown/CSV/HTML table 互转', href: 'https://tableconvert.com', icon: 'Table', category: '文本工具', target: '_blank' },
  { id: 'local-audio-convert', title: '本地音频转换', description: '浏览器内 WAV/MP3/OGG 互转', href: 'https://localaudioconvert.com', icon: 'AudioLines', category: '媒体工具', target: '_blank' },
  { id: 'tinypng', title: 'TinyPNG 压缩', description: '老牌智能压 PNG/JPG', href: 'https://tinypng.com', icon: 'Feather', category: '媒体工具', target: '_blank' },
  { id: 'har-viewer', title: 'HAR抓包解析器', description: '上传HAR抓包文件，解析请求响应', category: '测试工具', icon: 'FileSearch', href: '/tools/har-viewer' },
  { id: 'daily-quote', title: '今日文案', description: '随机文案 · 每日温暖', href: '/tools/daily-quote', icon: 'Quote', category: '日常工具' },
  { id: 'answer-book', title: '答案之书', description: '默念一个问题，翻开一页神秘答案', href: '/tools/answer-book', icon: 'BookOpen', category: '日常工具' },
]
