export type ApiEntry = {
  slug: string
  name: string
  desc: string
  category: string
  auth: 'No' | 'ApiKey' | 'OAuth'
  https: boolean
  cors: 'Yes' | 'No' | 'Unknown'
  commercial: 'Yes' | 'No' | 'Unknown'
  docs: string
  baseUrl: string
  example: string
  note?: string
}

export const apiList: ApiEntry[] = [
  {
    slug: 'open-meteo',
    name: 'Open-Meteo',
    desc: '无需 API Key 的天气预报接口（7天/每小时）',
    category: '天气',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://open-meteo.com/en/docs',
    baseUrl: 'https://api.open-meteo.com/v1',
    example:
      'https://api.open-meteo.com/v1/forecast?latitude=39.9&longitude=116.4&current_weather=true',
    note: '适合前端直连，非商用 1 万次/天免费',
  },
  {
    slug: 'rest-countries',
    name: 'REST Countries',
    desc: '国家信息：首都、国旗、货币、语言、经纬度',
    category: '地理',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://restcountries.com/',
    baseUrl: 'https://restcountries.com/v3.1',
    example: 'https://restcountries.com/v3.1/name/japan',
  },
  {
    slug: 'jikan',
    name: 'Jikan',
    desc: 'MyAnimeList 非官方 API，番剧/角色/评分',
    category: '动漫',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://jikan.moe/',
    baseUrl: 'https://api.jikan.moe/v4',
    example: 'https://api.jikan.moe/v4/anime?q=naruto&limit=5',
  },
  {
    slug: 'pokeapi',
    name: 'PokéAPI',
    desc: '1000+ 宝可梦数据：属性、技能、进化链',
    category: '游戏',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://pokeapi.co/docs/v2',
    baseUrl: 'https://pokeapi.co/api/v2',
    example: 'https://pokeapi.co/api/v2/pokemon/pikachu',
  },
  {
    slug: 'jsonplaceholder',
    name: 'JSONPlaceholder',
    desc: '前端练手专用假 REST 数据（post/user/todo）',
    category: '测试数据',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://jsonplaceholder.typicode.com/',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    example: 'https://jsonplaceholder.typicode.com/users',
  },
  {
    slug: 'dog-ceo',
    name: 'Dog CEO',
    desc: '随机狗狗图片，按品种分类',
    category: '动物',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://dog.ceo/dog-api/',
    baseUrl: 'https://dog.ceo/api',
    example: 'https://dog.ceo/api/breeds/image/random',
  },
  {
    slug: 'cat-facts',
    name: 'Cat Facts',
    desc: '随机猫猫冷知识',
    category: '动物',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://alexwohlbruck.github.io/cat-facts/',
    baseUrl: 'https://catfact.ninja',
    example: 'https://catfact.ninja/fact',
  },
  {
    slug: 'randomfox',
    name: 'RandomFox',
    desc: '每次请求返回一张随机狐狸图',
    category: '动物',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://randomfox.ca/',
    baseUrl: 'https://randomfox.ca',
    example: 'https://randomfox.ca/floof',
  },
  {
    slug: 'open-library',
    name: 'Open Library',
    desc: '开放图书数据：书名/作者/封面/ISBN',
    category: '图书',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://openlibrary.org/developers/api',
    baseUrl: 'https://openlibrary.org/api',
    example: 'https://openlibrary.org/api/books?bibkeys=ISBN:9780140328721&format=json',
  },
  {
    slug: 'quotable',
    name: 'Quotable',
    desc: '随机名人名言，支持作者/标签过滤',
    category: '文本',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://github.com/lukePeavey/quotable',
    baseUrl: 'https://api.quotable.io',
    example: 'https://api.quotable.io/random',
  },
  {
    slug: 'lorem-picsum',
    name: 'Lorem Picsum',
    desc: '随机占位图片，可指定尺寸/灰度/模糊',
    category: '图片',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://picsum.photos/',
    baseUrl: 'https://picsum.photos',
    example: 'https/200/300',
  },
  {
    slug: 'random-user',
    name: 'Random User Generator',
    desc: '生成假用户：姓名/头像/邮箱/地址',
    category: '测试数据',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://randomuser.me/',
    baseUrl: 'https://randomuser.me/api',
    example: 'https://randomuser.me/api/?results=3',
  },
  {
    slug: 'nasa-apod',
    name: 'NASA APOD',
    desc: '每日天文图（需免费 key，demo 用 demo_key）',
    category: '图片',
    auth: 'ApiKey',
    https: true,
    cors: 'Yes',
    commercial: 'Unknown',
    docs: 'https://api.nasa.gov/',
    baseUrl: 'https://api.nasa.gov/planetary',
    example:
      'https://api.nasa.gov/planetary/apod?api_key=demo_key',
    note: '前端 demo 可用 demo_key，生产去 nasa.gov 申请',
  },
  {
    slug: 'coingecko',
    name: 'CoinGecko',
    desc: '加密货币价格/市值/涨跌（部分端点免 key）',
    category: '金融',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Unknown',
    docs: 'https://docs.coingecko.com/',
    baseUrl: 'https://api.coingecko.com/api/v3',
    example: 'https://api.coingecko.com/api/v3/ping',
  },
  {
    slug: 'httpbin',
    name: 'httpbin',
    desc: 'HTTP 请求/响应测试（延迟/状态码/headers）',
    category: '测试数据',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://httpbin.org/',
    baseUrl: 'https://httpbin.org',
    example: 'https://httpbin.org/json',
  },
  {
    slug: 'swapi',
    name: 'SWAPI',
    desc: '星球大战官方向数据：人物/飞船/星球/电影',
    category: '影视',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://swapi.dev/',
    baseUrl: 'https://swapi.dev/api',
    example: 'https://swapi.dev/api/people/1/',
  },
  {
    slug: 'dummyjson',
    name: 'DummyJSON',
    desc: '假电商数据：商品/购物车/用户，支持 REST 方法',
    category: '测试数据',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://dummy[](@replace=10001)/',
    baseUrl: 'https://dummyjson.com',
    example: 'https://dummy叶json.com/products?limit=5',
  },
  {
    slug: 'reqres',
    name: 'ReqRes',
    desc: '前端联调用 REST 测试接口（用户增删改查）',
    category: '测试数据',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://reqres.in/',
    baseUrl: 'https://reqres.in/api',
    example: 'https://reqres.in/api/users?page=2',
  },
  {
    slug: 'bored-api',
    name: 'Bored API',
    desc: '随机给你一个“今天干点啥”的活动建议',
    category: '生活',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://www.boredapi.com/documentation',
    baseUrl: 'https://www.boredapi.com/api',
    example: 'https://www.boredapi.com/api/activity',
  },
  {
    slug: 'advice-slip',
    name: 'Advice Slip',
    desc: '随机人生建议一句话',
    category: '文本',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://api.adviceslip.com/',
    baseUrl: 'https://api.adviceslip.com',
    example: 'https://api.adviceslip.com/advice',
  },
  {
    slug: 'poetrydb',
    name: 'PoetryDB',
    desc: '公开诗歌库，按作者/标题/关键词检索',
    category: '文本',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://poetrydb.org/',
    baseUrl: 'https://poetrydb.org',
    example: 'https://poetrydb.org/author/Emily Dickinson',
  },
  {
    slug: 'datamuse',
    name: 'Datamuse',
    desc: '联想词/近义词/押韵词查询，写文案好用',
    category: '文本',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://www.datamuse.com/api/',
    baseUrl: 'https://api.datamuse.com',
    example: 'https://api.datamuse.com/words?rel_rhy=love&max=5',
  },
  {
    slug: 'free-dictionary',
    name: 'Free Dictionary',
    desc: '英文单词释义、音标、例句',
    category: '文本',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://dictionaryapi.dev/',
    baseUrl: 'https://api.dictionaryapi.dev/api/v2',
    example: 'https://api.dictionaryapi.dev/api/v2/entries/en/hello',
  },
  {
    slug: 'usgs-earthquake',
    name: 'USGS Earthquake',
    desc: '全球实时地震数据（美国政府公开数据）',
    category: '政府公开数据',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://earthquake.usgs.gov/fdsnws/event/1/',
    baseUrl: 'https://earthquake.usgs.gov/fdsnws/event/1',
    example: 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&limit=5',
  },
  {
    slug: 'world-bank',
    name: 'World Bank',
    desc: '全球经济发展指标（GDP/人口/教育等）',
    category: '政府公开数据',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392',
    baseUrl: 'https://api.worldbank.org/v2',
    example: 'https://api.worldbank.org/v2/country/CHN/indicator/NY.GDP.MKTP.CD?format=json',
  },
  {
    slug: 'open-food-facts',
    name: 'Open Food Facts',
    desc: '全球食品成分/营养数据库',
    category: '食物',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://world.openfoodfacts.org/data',
    baseUrl: 'https://world.openfoodfacts.org/api/v0',
    example: 'https://world.openfoodfacts.org/api/v0/product/737628064502.json',
  },
  {
    slug: 'the-meal-db',
    name: 'TheMealDB',
    desc: '免费套餐食谱（部分需 key，基础查询免 key）',
    category: '食物',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Unknown',
    docs: 'https://www.themealdb.com/api.php',
    baseUrl: 'https://www.themealdb.com/api/json/v1/1',
    example: 'https://www.themealdb.com/api/json/v1/1/random.php',
    note: '基础随机/按首字母查询免 key，高级功能需申请',
  },
  {
    slug: 'studio-ghibli',
    name: 'Studio Ghibli API',
    desc: '吉卜力电影/角色/场景数据（粉丝项目）',
    category: '影视',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Unknown',
    docs: 'https://ghibliapi.vercel.app/',
    baseUrl: 'https://ghibliapi.vercel.app',
    example: 'https://ghibliapi.vercel.app/films',
  },
  {
    slug: 'http-cats',
    name: 'HTTP Cats',
    desc: '每个 HTTP 状态码配一张猫图（调试用）',
    category: '开发工具',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://http.cat/',
    baseUrl: 'https://http.cat',
    example: 'https://http.cat/404',
  },
  {
    slug: 'placekitten',
    name: 'PlaceKitten',
    desc: '按尺寸返回占位猫图（老牌占位图服务）',
    category: '图片',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://placekitten.com/',
    baseUrl: 'https://placekitten.com',
    example: 'https://placekitten.com/200/300',
  },
  {
    slug: 'universities',
    name: 'Universities API',
    desc: '全球大学域名/名称查询',
    category: '教育',
    auth: 'No',
    https: true,
    cors: 'Yes',
    commercial: 'Yes',
    docs: 'https://github.com/Hipo/university-domains-list',
    baseUrl: 'http://universities.hipolabs.com',
    example: 'http://universities.hipolabs.com/search?country=China',
    note: '该接口为 HTTP，生产环境建议后端代理一道',
  },
]